import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CryptoVerse",
  description: "Generated by create next app",
};


const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '700'], // Add the weights you want to use
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
